language: d

script: ./.travis.sh
sudo: false

jobs:
  include:
    # =============================== Test Stage ===============================
    - stage: test
      d: ldc
      os: linux
      env: TEST_TARGET_ARCH=x86_64
      after_success:
        - bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN} -s .cov
    - d: ldc
      os: linux
      env: TEST_TARGET_ARCH=x86_64
    - d: ldc-latest-ci
      os: linux
      env: TEST_TARGET_ARCH=x86_64
    - d: dmd
      os: linux
      env: TEST_TARGET_ARCH=x86_64
    - d: dmd-nightly
      os: linux
      env: TEST_TARGET_ARCH=x86_64
    - d: ldc
      os: linux
      env: TEST_TARGET_ARCH=x86
      addons:
        apt:
          packages:
            - gcc-multilib
    - d: dmd
      os: linux
      env: TEST_TARGET_ARCH=x86
      addons:
        apt:
          packages:
            - gcc-multilib
    - d: ldc
      os: osx
      env: TEST_TARGET_ARCH=x86_64
    - d: dmd
      os: osx
      env: TEST_TARGET_ARCH=x86_64
    # ========================== Documentation Stage  ==========================
    - stage: Documentation
      d: ldc
      os: linux
      script:
        - echo "Deploying to GitHub pages ..." && dub run gendoc -y
        - dub run gendoc:candydoc -y -- --gendocConfig=candydoc --gendocTarget=docs/candydoc
      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: docs
          github_token: $GH_REPO_TOKEN
          on:
            tags: false
            branch: master
    # ========================== GitHub Release Stage ==========================
    - stage: GitHub Release
      d: ldc
      os: linux
      script: echo "Deploying to GitHub releases ..." && ./.travis-release.sh
      deploy:
        provider: releases
        api_key: $GH_REPO_TOKEN
        file_glob: true
        file: gendoc-*.tar.gz
        skip_cleanup: true
        on:
          repo: shoo/gendoc
          tags: true
    - d: ldc
      os: osx
      script: echo "Deploying to GitHub releases ..." && ./.travis-release.sh
      deploy:
        provider: releases
        api_key: $GH_REPO_TOKEN
        file_glob: true
        file: gendoc-*.tar.gz
        skip_cleanup: true
        on:
          repo: shoo/gendoc
          tags: true
    - d: dmd
      os: linux
      language: generic
      sudo: yes
      script: echo "Deploying to GitHub releases ..." && ARCH=32 ./.travis-release-windows.sh
      addons:
        apt:
          packages:
            - p7zip-full
      deploy:
        provider: releases
        api_key: $GH_REPO_TOKEN
        file_glob: true
        file: gendoc-*.zip
        skip_cleanup: true
        on:
          repo: shoo/gendoc
          tags: true
    - d: dmd
      os: linux
      language: generic
      sudo: yes
      script: echo "Deploying to GitHub releases ..." && ARCH=64 ./.travis-release-windows.sh
      addons:
        apt:
          packages:
            - p7zip-full
      deploy:
        provider: releases
        file_glob: true
        file: gendoc-*.zip
        skip_cleanup: true
        on:
          repo: shoo/gendoc
          tags: true
stages:
  - name: test
    if: type = pull_request or (type = push and branch = master)
  - name: Documentation
    if: type = push and branch = master
  - name: GitHub Release