language: d

d:
  - dmd
  - ldc

os:
  - linux
#  - osx

env:
  - ARCH=x86_64
  - ARCH=x86

branches:
  only:
    - master

script: ./.travis.sh

sudo: false

addons:
  apt:
    packages:
      - gcc-multilib
